# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acddd08abdb4415eed66639e983165f2148ccd283fb4ed10576c89f43286ed48c9b9d858a71eec6b96077017c34a18ace28be932bf8992d9458a6120ff1509b9

test:
  secret_key_base: 759af53371f25dfdc090d7a186aaf5c3ad8d38e078ddd1f50fb72758ea55421cb6ed5d8898ee8ebc6928c1b3ee1beb2a3225b2321f8aa6df23322d449df7d8ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
